/**
 * Generates a TypeScript interface per Avro record from the `.avsc` files in
 * this directory, plus a barrel that re-exports them.
 *
 * Run: `bun packages/schemas/codegen.ts`
 *
 * Deliberately small and bespoke: at five flat records the type mapping is the
 * lesson, not a dependency. The moment a schema needs nested records, arrays,
 * maps, or unions, `resolveType` throws loudly — that's the signal to reach for
 * a real generator rather than silently emit `any`.
 */

import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";

interface AvroComplex {
  logicalType?: string;
  name?: string;
  symbols?: string[];
  type: string;
}
type AvroType = string | AvroComplex | AvroType[];
interface AvroField {
  name: string;
  type: AvroType;
}
interface AvroRecord {
  fields: AvroField[];
  name: string;
  namespace?: string;
  type: "record";
}

/** Avro primitive → TS. uuid/string land here as `string`, long-based instants as `number`. */
const PRIMITIVE_TS: Record<string, string> = {
  string: "string",
  bytes: "string",
  int: "number",
  long: "number",
  float: "number",
  double: "number",
  boolean: "boolean",
  null: "null",
};

/**
 * Maps one Avro field type to a TS type string. Named enums are collected into
 * `enums` (keyed by name) so they can be emitted once, ahead of the interface
 * that references them.
 */
const resolveType = (type: AvroType, enums: Map<string, string>): string => {
  if (typeof type === "string") {
    const ts = PRIMITIVE_TS[type];
    if (!ts) {
      throw new Error(`Unsupported Avro primitive: ${type}`);
    }
    return ts;
  }

  if (Array.isArray(type)) {
    throw new Error(
      `Unions are unsupported at this stage (every field is required by design): ${JSON.stringify(type)}`
    );
  }

  if (type.type === "enum") {
    if (!(type.name && type.symbols)) {
      throw new Error(`Malformed enum: ${JSON.stringify(type)}`);
    }
    const union = type.symbols.map((s) => `"${s}"`).join(" | ");
    enums.set(type.name, `export type ${type.name} = ${union};`);
    return type.name;
  }

  /**
   * A logical type (uuid, timestamp-millis) is semantics over a primitive, so
   * on the TS side it collapses to that primitive's type — `string` / `number`.
   * This is the same erasure that happens on the wire.
   */
  const ts = PRIMITIVE_TS[type.type];
  if (!ts) {
    throw new Error(`Unsupported Avro type: ${JSON.stringify(type)}`);
  }
  return ts;
};

/** Renders a record into its enum definitions + interface, and the names to export. */
const generate = (record: AvroRecord): { code: string; names: string[] } => {
  const enums = new Map<string, string>();
  const fields = record.fields.map(
    (f) => `  ${f.name}: ${resolveType(f.type, enums)};`
  );

  const blocks = [...enums.values()];
  blocks.push(`export interface ${record.name} {\n${fields.join("\n")}\n}`);

  return { code: blocks.join("\n\n"), names: [...enums.keys(), record.name] };
};

const SCHEMA_DIR = new URL(".", import.meta.url).pathname;
const OUT_DIR = `${SCHEMA_DIR}generated/ts`;

const BANNER = "// GENERATED by codegen.ts — do not edit by hand.";

const main = async () => {
  await mkdir(OUT_DIR, { recursive: true });

  const files = (await readdir(SCHEMA_DIR))
    .filter((f) => f.endsWith(".avsc"))
    .sort();

  const reexports: string[] = [];

  for (const file of files) {
    const record: AvroRecord = JSON.parse(
      await readFile(`${SCHEMA_DIR}${file}`, "utf8")
    );
    const { code, names } = generate(record);

    await writeFile(
      `${OUT_DIR}/${record.name}.ts`,
      `${BANNER}\n// Source: ${file}\n\n${code}\n`
    );
    reexports.push(
      `export type { ${names.join(", ")} } from "./${record.name}";`
    );
    console.log(`✓ ${file.padEnd(22)} → generated/ts/${record.name}.ts`);
  }

  await writeFile(
    `${OUT_DIR}/index.ts`,
    `${BANNER}\n\n${reexports.join("\n")}\n`
  );
  console.log(
    `✓ barrel               → generated/ts/index.ts (${files.length} records)`
  );
};

await main();
